apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finovra # This is the name you'll see in the UI/CLI
  namespace: argocd # Applications always live in the argocd namespace itself
spec:
  project: default # Which AppProject this belongs to (default for now — the optional Running ArgoCD Safely module covers custom projects)
  source:
    repoURL: https://github.com/pratyushmk/gitops.git
    targetRevision: main # Branch, tag, or commit SHA to track
    path: helm-chart # Path within the repo to the manifests to apply
  destination:
    server: https://kubernetes.default.svc # "This same cluster" — ArgoCD's own cluster
    namespace: finovra # Namespace to deploy into
  syncPolicy:
    automated: {
        prune: true, # Delete resources that are no longer tracked in Git,
        selfHeal: true, # Automatically apply changes if they drift from the Git state
      }
    syncOptions:
      - CreateNamespace=true # Let ArgoCD create the namespace if it doesn't exist
